name: Create Spacelift Stack

on:
 push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Create Spacelift Stack
        run: |
          curl -X POST https://api.spacelift.io/graphql \
            -H "Authorization: Bearer ${{ secrets.SPACELIFT_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation CreateStack($input: StackCreateInput!) { stackCreate(input: $input) { id name } }",
              "variables": {
                "input": {
                  "name": "demo-gh-action-stack",
                  "repository": "eswar21-sudo/dynamodb",  # format: <org>/<repo>
                  "branch": "main",
                  "space": "root",  # default space
                  "administrative": true,
                  "terraformProvider": "AWS",
                  "labels": ["github-action"]
                }
              }
            }'
