name: Create Spacelift Stack

on:
  workflow_dispatch:

jobs:
  create-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Create Spacelift Stack
        env:
          SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
          SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
        run: |
          spacectl stack create \
            --name example-stack \
            --repository github.com/eswar21-sudo/dynamodb \
            --branch main \
            --space-id root \
            --project-root . \
            --manage-state true \
            --autodeploy true
